name: file_utils
description: Utility functions for working with files.
environment:
  sdk: ">=2.13.1 <3.0.0"
dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
dependencies:
  args: ^2.2.0
  glob: ^2.0.1
  path: ^1.8.0
